// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: GGMAP

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////
void Swing_Animation(lv_obj_t * TargetObject, int delay);


// SCREEN: ui_ScreenScreen1
void ui_ScreenScreen1_screen_init(void);
void ui_event_ScreenScreen1(lv_event_t * e);
lv_obj_t * ui_ScreenScreen1;
lv_obj_t * ui_Screen1ContainerContainer2;
lv_obj_t * ui_Screen1PanelHeadline;
lv_obj_t * ui_Screen1LabelLabel4;
lv_obj_t * ui_Screen1ContainerMainContainer;
lv_obj_t * ui_Screen1PanelNavigatePanel;
void ui_event_Screen1ButtonButton1(lv_event_t * e);
lv_obj_t * ui_Screen1ButtonButton1;
lv_obj_t * ui_Screen1ImageImage3;
lv_obj_t * ui_Screen1LabelLabel13;
// CUSTOM VARIABLES


// SCREEN: ui_ScreenScreen2
void ui_ScreenScreen2_screen_init(void);
void ui_event_ScreenScreen2(lv_event_t * e);
lv_obj_t * ui_ScreenScreen2;
lv_obj_t * ui_Screen2ContainerContainer1;
lv_obj_t * ui_Screen2PanelHeadline1;
lv_obj_t * ui_Screen2LabelLabel7;
lv_obj_t * ui_Screen2SpinnerSpinner2;
lv_obj_t * ui_Screen2LabelLabel8;
lv_obj_t * ui_Screen2ContainerMainContainer1;
lv_obj_t * ui_Screen2PanelNavigatePanel1;
lv_obj_t * ui_Screen2ImageImage2;
lv_obj_t * ui_Screen2LabelLabel9;
lv_obj_t * ui_Screen2PanelNavigateDirection1;
lv_obj_t * ui_Screen2LabelLabel10;
lv_obj_t * ui_Screen2LabelLabel11;
lv_obj_t * ui_Screen2LabelLabel12;
// CUSTOM VARIABLES

// EVENTS
lv_obj_t * ui_Startevents___initial_actions0;

// IMAGES AND IMAGE SETS
const lv_image_dsc_t * ui_imgset_20241025_110411_[2] = {&ui_img_20241025_110411_0000_png, &ui_img_20241025_110411_0001_png};
const lv_image_dsc_t * ui_imgset_dog_[3] = {&ui_img_dog_0_png, &ui_img_dog_1_png, &ui_img_dog_2_png};
const lv_image_dsc_t * ui_imgset_h_20250228_131139_[1] = {&ui_img_h_20250228_131139_0000_png};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////
void Swing_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_malloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 1000);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_opacity);
    lv_anim_set_values(&PropertyAnimation_0, 0, 255);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_linear);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, LV_ANIM_REPEAT_INFINITE);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, true);
    lv_anim_set_get_value_cb(&PropertyAnimation_0, &_ui_anim_callback_get_opacity);
    lv_anim_start(&PropertyAnimation_0);

}

///////////////////// FUNCTIONS ////////////////////
void ui_event_ScreenScreen1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOADED) {
        homeScreenLoadCb(e);
    }
}

void ui_event_Screen1ButtonButton1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_KEY &&  lv_event_get_key(e) == LV_KEY_ENTER) {
        _ui_screen_change(&ui_ScreenScreen2, LV_SCR_LOAD_ANIM_MOVE_LEFT, 200, 0, &ui_ScreenScreen2_screen_init);
    }
}

void ui_event_ScreenScreen2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOADED) {
        appScreenLoadCb(e);
        Swing_Animation(ui_Screen2ImageImage2, 0);
    }
    if(event_code == LV_EVENT_KEY &&  lv_event_get_key(e) == LV_KEY_ESC) {
        _ui_screen_change(&ui_ScreenScreen1, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 200, 0, &ui_ScreenScreen1_screen_init);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_display_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_ScreenScreen1_screen_init();
    ui_ScreenScreen2_screen_init();
    ui_Startevents___initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_ScreenScreen1);
}
