// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: GGMAP

#ifndef _GGMAP_UI_H
#define _GGMAP_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "lv_i18n/lv_i18n.h"
extern lv_group_t * master_group;
lv_group_t * master_group;
#include "ui_helpers.h"
#include "ui_events.h"

void Swing_Animation(lv_obj_t * TargetObject, int delay);

// SCREEN: ui_ScreenScreen1
void ui_ScreenScreen1_screen_init(void);
void ui_event_ScreenScreen1(lv_event_t * e);
extern lv_obj_t * ui_ScreenScreen1;
extern lv_obj_t * ui_Screen1ContainerContainer2;
extern lv_obj_t * ui_Screen1PanelHeadline;
extern lv_obj_t * ui_Screen1LabelLabel4;
extern lv_obj_t * ui_Screen1ContainerMainContainer;
extern lv_obj_t * ui_Screen1PanelNavigatePanel;
void ui_event_Screen1ButtonButton1(lv_event_t * e);
extern lv_obj_t * ui_Screen1ButtonButton1;
extern lv_obj_t * ui_Screen1ImageImage3;
extern lv_obj_t * ui_Screen1LabelLabel13;
// CUSTOM VARIABLES

// SCREEN: ui_ScreenScreen2
void ui_ScreenScreen2_screen_init(void);
void ui_event_ScreenScreen2(lv_event_t * e);
extern lv_obj_t * ui_ScreenScreen2;
extern lv_obj_t * ui_Screen2ContainerContainer1;
extern lv_obj_t * ui_Screen2PanelHeadline1;
extern lv_obj_t * ui_Screen2LabelLabel7;
extern lv_obj_t * ui_Screen2SpinnerSpinner2;
extern lv_obj_t * ui_Screen2LabelLabel8;
extern lv_obj_t * ui_Screen2ContainerMainContainer1;
extern lv_obj_t * ui_Screen2PanelNavigatePanel1;
extern lv_obj_t * ui_Screen2ImageImage2;
extern lv_obj_t * ui_Screen2LabelLabel9;
extern lv_obj_t * ui_Screen2PanelNavigateDirection1;
extern lv_obj_t * ui_Screen2LabelLabel10;
extern lv_obj_t * ui_Screen2LabelLabel11;
extern lv_obj_t * ui_Screen2LabelLabel12;
// CUSTOM VARIABLES

// EVENTS

extern lv_obj_t * ui_Startevents___initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_rightturn_png);    // assets/RightTurn.png
LV_IMG_DECLARE(ui_img_20241025_110411_0000_png);    // assets/20241025_110411_0000.png
LV_IMG_DECLARE(ui_img_20241025_110411_0001_png);    // assets/20241025_110411_0001.png
LV_IMG_DECLARE(ui_img_dog_0_png);    // assets/Dog_0.png
LV_IMG_DECLARE(ui_img_dog_1_png);    // assets/Dog_1.png
LV_IMG_DECLARE(ui_img_dog_2_png);    // assets/Dog_2.png
LV_IMG_DECLARE(ui_img_h_20250228_131139_0000_png);    // assets/H_20250228_131139_0000.png

// FONTS
LV_FONT_DECLARE(ui_font_Arial12);
LV_FONT_DECLARE(ui_font_Arial14);

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
