// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: PetSample

#include "ui.h"

void appNavClose(lv_event_t * e)
{
	// Your code here
}

void homeScreenLoadCb(lv_event_t * e)
{
	lv_group_remove_all_objs(master_group);
	lv_group_add_obj(master_group, ui_Screen1ButtonButton1);
	// Your code here
}

void appScreenLoadCb(lv_event_t * e)
{
	lv_group_remove_all_objs(master_group);
	lv_group_add_obj(master_group, ui_ScreenScreen2);
	// Your code here
}
