// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: GGMAP

#include "ui.h"

void ui_ScreenScreen2_screen_init(void)
{
    ui_ScreenScreen2 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_ScreenScreen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_flex_flow(ui_ScreenScreen2, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_ScreenScreen2, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_END);
    lv_obj_set_style_pad_left(ui_ScreenScreen2, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ScreenScreen2, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ScreenScreen2, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ScreenScreen2, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ScreenScreen2, &ui_font_Arial14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen2ContainerContainer1 = lv_obj_create(ui_ScreenScreen2);
    lv_obj_remove_style_all(ui_Screen2ContainerContainer1);
    lv_obj_set_width(ui_Screen2ContainerContainer1, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_Screen2ContainerContainer1, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_Screen2ContainerContainer1, 0);
    lv_obj_set_y(ui_Screen2ContainerContainer1, -1);
    lv_obj_set_align(ui_Screen2ContainerContainer1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Screen2ContainerContainer1, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Screen2ContainerContainer1, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_Screen2ContainerContainer1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(ui_Screen2ContainerContainer1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Screen2ContainerContainer1, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen2PanelHeadline1 = lv_obj_create(ui_Screen2ContainerContainer1);
    lv_obj_set_height(ui_Screen2PanelHeadline1, 30);
    lv_obj_set_width(ui_Screen2PanelHeadline1, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_x(ui_Screen2PanelHeadline1, 0);
    lv_obj_set_y(ui_Screen2PanelHeadline1, -1);
    lv_obj_set_align(ui_Screen2PanelHeadline1, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Screen2PanelHeadline1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Screen2LabelLabel7 = lv_label_create(ui_Screen2PanelHeadline1);
    lv_obj_set_width(ui_Screen2LabelLabel7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Screen2LabelLabel7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Screen2LabelLabel7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Screen2LabelLabel7, "Chỉ đường uProject Maps");

    ui_Screen2SpinnerSpinner2 = lv_spinner_create(ui_Screen2ContainerContainer1);
    //lv_spinner_set_anim_params(ui_Screen2SpinnerSpinner2, 1000, 90);
    lv_obj_set_width(ui_Screen2SpinnerSpinner2, 20);
    lv_obj_set_height(ui_Screen2SpinnerSpinner2, 20);
    lv_obj_set_align(ui_Screen2SpinnerSpinner2, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Screen2SpinnerSpinner2, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_style_arc_width(ui_Screen2SpinnerSpinner2, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_width(ui_Screen2SpinnerSpinner2, 3, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_Screen2LabelLabel8 = lv_label_create(ui_Screen2ContainerContainer1);
    lv_obj_set_width(ui_Screen2LabelLabel8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Screen2LabelLabel8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Screen2LabelLabel8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Screen2LabelLabel8, "đang đi");

    ui_Screen2ContainerMainContainer1 = lv_obj_create(ui_ScreenScreen2);
    lv_obj_remove_style_all(ui_Screen2ContainerMainContainer1);
    lv_obj_set_width(ui_Screen2ContainerMainContainer1, 310);
    lv_obj_set_height(ui_Screen2ContainerMainContainer1, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_Screen2ContainerMainContainer1, 0);
    lv_obj_set_y(ui_Screen2ContainerMainContainer1, -1);
    lv_obj_set_align(ui_Screen2ContainerMainContainer1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Screen2ContainerMainContainer1, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Screen2ContainerMainContainer1, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_END,
                          LV_FLEX_ALIGN_END);
    lv_obj_remove_flag(ui_Screen2ContainerMainContainer1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_Screen2ContainerMainContainer1, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Screen2ContainerMainContainer1, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Screen2ContainerMainContainer1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Screen2ContainerMainContainer1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen2PanelNavigatePanel1 = lv_obj_create(ui_Screen2ContainerMainContainer1);
    lv_obj_set_width(ui_Screen2PanelNavigatePanel1, 120);
    lv_obj_set_height(ui_Screen2PanelNavigatePanel1, 120);
    lv_obj_set_x(ui_Screen2PanelNavigatePanel1, 0);
    lv_obj_set_y(ui_Screen2PanelNavigatePanel1, 1);
    lv_obj_set_align(ui_Screen2PanelNavigatePanel1, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Screen2PanelNavigatePanel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Screen2ImageImage2 = lv_image_create(ui_Screen2PanelNavigatePanel1);
    lv_image_set_src(ui_Screen2ImageImage2, &ui_img_rightturn_png);
    lv_obj_set_width(ui_Screen2ImageImage2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Screen2ImageImage2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Screen2ImageImage2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Screen2ImageImage2, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Screen2ImageImage2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Screen2LabelLabel9 = lv_label_create(ui_Screen2PanelNavigatePanel1);
    lv_obj_set_width(ui_Screen2LabelLabel9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Screen2LabelLabel9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Screen2LabelLabel9, 25);
    lv_obj_set_y(ui_Screen2LabelLabel9, 27);
    lv_obj_set_align(ui_Screen2LabelLabel9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Screen2LabelLabel9, "100M");

    ui_Screen2PanelNavigateDirection1 = lv_obj_create(ui_Screen2ContainerMainContainer1);
    lv_obj_set_width(ui_Screen2PanelNavigateDirection1, 170);
    lv_obj_set_height(ui_Screen2PanelNavigateDirection1, 120);
    lv_obj_set_align(ui_Screen2PanelNavigateDirection1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Screen2PanelNavigateDirection1, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Screen2PanelNavigateDirection1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_Screen2PanelNavigateDirection1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Screen2LabelLabel10 = lv_label_create(ui_Screen2PanelNavigateDirection1);
    lv_obj_set_width(ui_Screen2LabelLabel10, 125);
    lv_obj_set_height(ui_Screen2LabelLabel10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Screen2LabelLabel10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Screen2LabelLabel10, "100m nữa");

    ui_Screen2LabelLabel12 = lv_label_create(ui_Screen2PanelNavigateDirection1);
    lv_obj_set_width(ui_Screen2LabelLabel12, 125);
    lv_obj_set_height(ui_Screen2LabelLabel12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Screen2LabelLabel12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Screen2LabelLabel12, "Vào đường Phạm Văn Đồng");

    lv_obj_add_event_cb(ui_ScreenScreen2, ui_event_ScreenScreen2, LV_EVENT_ALL, NULL);

}
