// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: GGMAP

#include "ui.h"

void ui_ScreenScreen1_screen_init(void)
{
    ui_ScreenScreen1 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_ScreenScreen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_flex_flow(ui_ScreenScreen1, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_ScreenScreen1, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_END);
    lv_obj_set_style_pad_left(ui_ScreenScreen1, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ScreenScreen1, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ScreenScreen1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ScreenScreen1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ScreenScreen1, &ui_font_Arial14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen1ContainerContainer2 = lv_obj_create(ui_ScreenScreen1);
    lv_obj_remove_style_all(ui_Screen1ContainerContainer2);
    lv_obj_set_width(ui_Screen1ContainerContainer2, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_Screen1ContainerContainer2, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_Screen1ContainerContainer2, 0);
    lv_obj_set_y(ui_Screen1ContainerContainer2, -1);
    lv_obj_set_align(ui_Screen1ContainerContainer2, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Screen1ContainerContainer2, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Screen1ContainerContainer2, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Screen1ContainerContainer2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(ui_Screen1ContainerContainer2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Screen1ContainerContainer2, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen1PanelHeadline = lv_obj_create(ui_Screen1ContainerContainer2);
    lv_obj_set_height(ui_Screen1PanelHeadline, 30);
    lv_obj_set_width(ui_Screen1PanelHeadline, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_x(ui_Screen1PanelHeadline, 0);
    lv_obj_set_y(ui_Screen1PanelHeadline, -1);
    lv_obj_set_align(ui_Screen1PanelHeadline, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Screen1PanelHeadline, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Screen1LabelLabel4 = lv_label_create(ui_Screen1PanelHeadline);
    lv_obj_set_width(ui_Screen1LabelLabel4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Screen1LabelLabel4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Screen1LabelLabel4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Screen1LabelLabel4, "uProject Dashboard");

    ui_Screen1ContainerMainContainer = lv_obj_create(ui_ScreenScreen1);
    lv_obj_remove_style_all(ui_Screen1ContainerMainContainer);
    lv_obj_set_width(ui_Screen1ContainerMainContainer, 310);
    lv_obj_set_height(ui_Screen1ContainerMainContainer, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_Screen1ContainerMainContainer, 0);
    lv_obj_set_y(ui_Screen1ContainerMainContainer, -1);
    lv_obj_set_align(ui_Screen1ContainerMainContainer, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Screen1ContainerMainContainer, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Screen1ContainerMainContainer, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER,
                          LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Screen1ContainerMainContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_Screen1ContainerMainContainer, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Screen1ContainerMainContainer, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Screen1ContainerMainContainer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Screen1ContainerMainContainer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen1PanelNavigatePanel = lv_obj_create(ui_Screen1ContainerMainContainer);
    lv_obj_set_width(ui_Screen1PanelNavigatePanel, 120);
    lv_obj_set_height(ui_Screen1PanelNavigatePanel, 120);
    lv_obj_set_x(ui_Screen1PanelNavigatePanel, 0);
    lv_obj_set_y(ui_Screen1PanelNavigatePanel, 1);
    lv_obj_set_align(ui_Screen1PanelNavigatePanel, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Screen1PanelNavigatePanel, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Screen1PanelNavigatePanel, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Screen1PanelNavigatePanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Screen1ButtonButton1 = lv_button_create(ui_Screen1PanelNavigatePanel);
    lv_obj_set_width(ui_Screen1ButtonButton1, 80);
    lv_obj_set_height(ui_Screen1ButtonButton1, 80);
    lv_obj_set_align(ui_Screen1ButtonButton1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Screen1ButtonButton1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Screen1ButtonButton1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Screen1ImageImage3 = lv_image_create(ui_Screen1ButtonButton1);
    lv_image_set_src(ui_Screen1ImageImage3, &ui_img_rightturn_png);
    lv_obj_set_width(ui_Screen1ImageImage3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Screen1ImageImage3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Screen1ImageImage3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Screen1ImageImage3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_EVENT_BUBBLE);     /// Flags
    lv_obj_remove_flag(ui_Screen1ImageImage3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Screen1LabelLabel13 = lv_label_create(ui_Screen1PanelNavigatePanel);
    lv_obj_set_width(ui_Screen1LabelLabel13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Screen1LabelLabel13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Screen1LabelLabel13, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Screen1LabelLabel13, "uProject Maps");

    lv_obj_add_event_cb(ui_Screen1ButtonButton1, ui_event_Screen1ButtonButton1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ScreenScreen1, ui_event_ScreenScreen1, LV_EVENT_ALL, NULL);

}
